### ISSUE TITLE
Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by ibigpapa** [Team-Silver-Sphere/SquadJS#100]
### Description of Issue
Node is giving warning 
`(node:12212) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
Possible EventEmitter memory leak detected.`

I enabled --trace-warnings
### Errors or Screenshots of Issue
```
Version: 1.4.1

SquadJS factory commencing building...
Getting config file...
Building Squad server...
Initialising connectors...
Starting discordClient connector...
Starting mysqlPool connector...
Loading plugins...
Loading plugin auto-tk-warn...
Loading plugin discord-admin-cam-logs...
Loading plugin discord-admin-request...
Loading plugin discord-teamkill...
Loading plugin mysql-log...
Watching server 1...
(node:12212) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:389:17)
    at Socket.addListener (events.js:405:10)
    at Socket.Readable.on (_stream_readable.js:853:35)
    at Socket.once (events.js:436:8)
    at file:///C:/servers/squadjs-current/SquadJS/squad-server/rcon/index.js:235:19
    at new Promise (<anonymous>)
    at Rcon.write (file:///C:/servers/squadjs-current/SquadJS/squad-server/rcon/index.js:179:12)
    at Rcon.execute (file:///C:/servers/squadjs-current/SquadJS/squad-server/rcon/index.js:54:17)
    at Rcon.getMapInfo (file:///C:/servers/squadjs-current/SquadJS/squad-server/rcon/index.js:58:33)
    at Timeout._onTimeout (file:///C:/servers/squadjs-current/SquadJS/squad-server/index.js:53:36)
```

### Squad Information
 * SquadJS Version:1.4.1
 * Squad Version:1.1.0.173.39994-4.23.1-SHIPPING

### System Information
 * Operating System: Windows 10
 * NodeJS Version:v14.5.0
 * Yarn Version: 1.22.4

**Comment by ibigpapa** [comment]
We started seeing this after enabling admin cam log.  It's not every time but a restart is required to fix it.  But appears to happen when we go in and out of admin cam "sometimes"

**Comment by ibigpapa** [comment]
Err, well we just disabled admin-cam-log and still getting this error.

**Comment by Thomas-Smyth** [comment]
The majority of SquadJS has been rewritten so I will close this.
