### ISSUE TITLE
Error Given on Discord Status

### ISSUE THREAD

**Issue by werewolfboy13** [Team-Silver-Sphere/SquadJS#123]
### Description of Issue

Randomly when the server goes over cap ex 100/98. The bot will stop updating embeds and will show "unknown" next to the map layer in the presence(discord status).

### Errors or Screenshots of Issue

TypeError: Cannot read property 'replace' of undefined
    at DiscordServerStatus.getEmbed (file:///C:/Users/Administrator/Desktop/Servers/Spaghetti-Bot/squad-server/plugins/discord-server-status.js:85:54)
    at DiscordServerStatus.update (file:///C:/Users/Administrator/Desktop/Servers/Spaghetti-Bot/squad-server/plugins/discord-server-status.js:64:33)

### Squad Information
 * SquadJS Version: current beta branch
 * Squad Version: current

### System Information
 * Operating System: windows server 2019
 * NodeJS Version: v12.19.1
 * Yarn Version: current

**Comment by werewolfboy13** [comment]
Issue is fixed with current branch/no longer in play.
