### ISSUE TITLE
If a player name has a special character an error throws in mySQL plugin.

### ISSUE THREAD

**Issue by werewolfboy13** [Team-Silver-Sphere/SquadJS#148]
### Description of Issue
If a player name has a special character like 😲 an error throws.
### Errors or Screenshots of Issue

[SquadServer][1] Updating player list...
DatabaseError [SequelizeDatabaseError]: Conversion from collation utf8mb4_unicode_ci into utf8_general_ci impossible for parameter
    at Query.formatError (C:\Users\Administrator\Desktop\Servers\Spaghetti-Bot\node_modules\sequelize\lib\dialects\mysql\query.js:239:16)
    at Query.run (C:\Users\Administrator\Desktop\Servers\Spaghetti-Bot\node_modules\sequelize\lib\dialects\mysql\query.js:54:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async C:\Users\Administrator\Desktop\Servers\Spaghetti-Bot\node_modules\sequelize\lib\sequelize.js:619:16
    at async MySQLQueryInterface.upsert (C:\Users\Administrator\Desktop\Servers\Spaghetti-Bot\node_modules\sequelize\lib\dialects\mysql\query-interface.js:52:12)
    at async Function.upsert (C:\Users\Administrator\Desktop\Servers\Spaghetti-Bot\node_modules\sequelize\lib\model.js:2482:20)
    at async DBLog.onPlayerWounded (file:///C:/Users/Administrator/Desktop/Servers/Spaghetti-Bot/squad-server/plugins/db-log.js:459:7) {
  parent: Error: Conversion from collation utf8mb4_unicode_ci into utf8_general_ci impossible for parameter
      at Packet.asError (C:\Users\Administrator\Desktop\Servers\Spaghetti-Bot\node_modules\mysql2\lib\packets\packet.js:712:17)
      at Execute.execute (C:\Users\Administrator\Desktop\Servers\Spaghetti-Bot\node_modules\mysql2\lib\commands\command.js:28:26)
      at Connection.handlePacket (C:\Users\Administrator\Desktop\Servers\Spaghetti-Bot\node_modules\mysql2\lib\connection.js:425:32)
      at PacketParser.onPacket (C:\Users\Administrator\Desktop\Servers\Spaghetti-Bot\node_modules\mysql2\lib\connection.js:75:12)
      at PacketParser.executeStart (C:\Users\Administrator\Desktop\Servers\Spaghetti-Bot\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\Administrator\Desktop\Servers\Spaghetti-Bot\node_modules\mysql2\lib\connection.js:82:25)
      at Socket.emit (events.js:315:20)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10) {
    code: undefined,
    errno: 3988,
    sqlState: 'HY000',
    sqlMessage: 'Conversion from collation utf8mb4_unicode_ci into utf8_general_ci impossible for parameter',
    sql: 'INSERT INTO `DBLog_SteamUsers` (`steamID`,`lastName`) VALUES (?,?) ON DUPLICATE KEY UPDATE `steamID`=VALUES(`steamID`),`lastName`=VALUES(`lastName`);',
    parameters: [ '76561198139352774', '¢OLE 😲' ]
  },
  original: Error: Conversion from collation utf8mb4_unicode_ci into utf8_general_ci impossible for parameter
      at Packet.asError (C:\Users\Administrator\Desktop\Servers\Spaghetti-Bot\node_modules\mysql2\lib\packets\packet.js:712:17)
      at Execute.execute (C:\Users\Administrator\Desktop\Servers\Spaghetti-Bot\node_modules\mysql2\lib\commands\command.js:28:26)
      at Connection.handlePacket (C:\Users\Administrator\Desktop\Servers\Spaghetti-Bot\node_modules\mysql2\lib\connection.js:425:32)
      at PacketParser.onPacket (C:\Users\Administrator\Desktop\Servers\Spaghetti-Bot\node_modules\mysql2\lib\connection.js:75:12)
      at PacketParser.executeStart (C:\Users\Administrator\Desktop\Servers\Spaghetti-Bot\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\Administrator\Desktop\Servers\Spaghetti-Bot\node_modules\mysql2\lib\connection.js:82:25)
      at Socket.emit (events.js:315:20)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10) {
    code: undefined,
    errno: 3988,
    sqlState: 'HY000',
    sqlMessage: 'Conversion from collation utf8mb4_unicode_ci into utf8_general_ci impossible for parameter',
    sql: 'INSERT INTO `DBLog_SteamUsers` (`steamID`,`lastName`) VALUES (?,?) ON DUPLICATE KEY UPDATE `steamID`=VALUES(`steamID`),`lastName`=VALUES(`lastName`);',
    parameters: [ '76561198139352774', '¢OLE 😲' ]
  },
  sql: 'INSERT INTO `DBLog_SteamUsers` (`steamID`,`lastName`) VALUES (?,?) ON DUPLICATE KEY UPDATE `steamID`=VALUES(`steamID`),`lastName`=VALUES(`lastName`);',
  parameters: [ '76561198139352774', '¢OLE 😲' ]
}

### Squad Information
 * SquadJS Version: Current beta branch
 * Squad Version: Current

### System Information
 * Operating System: Server 2016
 * NodeJS Version: 14
 * Yarn Version: current

**Comment by milutinke** [comment]
Try adding this to your connector settings below the "dialect" option in config.json.

This:
`"define": {
	"charset": "utf8mb4",
	"collate": "utf8mb4_unicode_ci"
}`

Also, run this in your DB: 
`ALTER DATABASE DBLog_SteamUsers CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;`

After that, it should be able to store emojis in the database.
I am going to integrate this in my fork of the repository and test it out.
