### ISSUE TITLE
DiscordKillFeed victim sometimes being undefined

### ISSUE THREAD

**Issue by LeventHAN** [Team-Silver-Sphere/SquadJS#208]
### Description of Issue
Using plugin discord kill feed.
Sometimes it throws that victim is undefined... (see error below)

### Errors or Screenshots of Issue
```js
[SquadServer][1] Successfully pinged the SquadJS API. Got back message: Pong.
[SquadServer][1] Updating player list...
[SquadServer][1] Updating player list...
[SquadServer][1] Updated player list.
[SquadServer][1] Updated player list.
(node:27856) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of null
    at DiscordKillFeed.onWound (file:///D:/rcon/SquadJS-94bb989a833111fbfd815f1603ba26d423734470/squad-server/plugins/discord-killfeed.js:71:28)
    at SquadServer.emit (events.js:315:20)
    at SquadServer.EventEmitter.emit (domain.js:467:12)
    at SquadLogParser.<anonymous> (file:///D:/rcon/SquadJS-94bb989a833111fbfd815f1603ba26d423734470/squad-server/index.js:241:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use node --trace-warnings ... to show where the warning was created)
(node:27856) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27856) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[SquadServer][1] Updating squad list...
[SquadServer][1] Updated squad list.
[SquadServer][1] Updating layer information...
[SquadServer][1] Updated layer information.
[SquadServer][1] Updating A2S information...
[SquadServer][1] Updated A2S information.
[SquadServer][1] Updating player list...
```

### Squad Information
 * Plugins: DiscordKillFeed
 * SquadJS Version: last / master
 * Squad Version: last

If potentially relevant, please provide regarding the state of the Squad server at the time of error, e.g. the current layer.

### System Information
 irrelevant

**Comment by LeventHAN** [comment]
An easy solution would be: `if (!info.victim) return;`
@Thomas-Smyth let me know if this might be an issue that @ect0s is having with victims/attackers being missed... That is why I did put this here.

**Comment by Thomas-Smyth** [comment]
Looks to be the same issue discussed in Discord.

**Comment by ect0s** [comment]
As of the recent [PR](https://github.com/Team-Silver-Sphere/SquadJS/pull/240), the plugin will now emit Unknown. 

Issue is tied to squad logs not containing enough information for us to reconstruct a wound event.
