### ISSUE TITLE
Server Status Bug

### ISSUE THREAD

**Issue by IgnisAlienus** [Team-Silver-Sphere/SquadJS#23]
### Description of Issue
Get this error in the cmd prompt for Server Status trying to import 'tinygradient'
### Errors or Screenshots of Issue

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'tinygradient' imported from c:\SquadJS\plugins\discord-server-status\index.js
    at packageResolve (internal/modules/esm/resolve.js:616:9)
    at moduleResolve (internal/modules/esm/resolve.js:655:14)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:748:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:42:40)
    at link (internal/modules/esm/module_job.js:41:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

### Squad Information
 * Plugins in Use: Discord Server Status
 * SquadJS Version: 1.0.10
 * Squad Version: b19.5

### System Information
 * Operating System: Windows
 * NodeJS Version: most recent
 * Yarn Version: most recent

**Comment by IgnisAlienus** [comment]
I had to do a cmd console using
npm i tinygradient 
with the folder set to the location of SquadJS/index.js

All good now.
